using UnityEngine;

namespace FlightSim
{
    /// <summary>
    /// Makes the aeroplane sound like one. It invents nothing of its own: it watches the numbers
    /// in Aircraft and turns them into volume and pitch.
    ///
    ///   * **engines** - two looping sounds playing at once, a quiet idle and a louder roar. The
    ///     throttle fades between them. Crossfading two recordings is how this is normally done,
    ///     because simply pitching one sound up makes a jet sound like a hairdryer.
    ///   * **wind** - gets louder and higher the faster you go, which is most of what "fast"
    ///     actually sounds like from inside a cockpit.
    ///   * **tyres** - only while the wheels are down AND touching the ground, and it fades out as
    ///     you slow down.
    ///   * **one-shots** - the gear thunk and the touchdown thump, each fired once when the thing
    ///     they describe actually happens.
    ///
    /// Every clip is generated by maths in AudioBank, not recorded, so nothing has to be
    /// downloaded and the project stays self-contained.
    ///
    /// All the AudioSources are made and filled in by the scene builder, so if one is missing this
    /// script simply skips it rather than throwing.
    /// </summary>
    [DisallowMultipleComponent]
    public class AircraftAudio : MonoBehaviour
    {
        [Header("Looping sources (set by the scene builder)")]
        [Tooltip("Engines at idle. Always playing; the throttle fades it out.")]
        public AudioSource idle;
        [Tooltip("Engines at power. Always playing; the throttle fades it in.")]
        public AudioSource power;
        [Tooltip("Airflow. Follows speed.")]
        public AudioSource wind;
        [Tooltip("Tyres on tarmac. Only while the wheels are actually rolling.")]
        public AudioSource tyres;
        [Tooltip("Reverse thrust, used by the landing in scene 4.")]
        public AudioSource reverse;

        [Header("One-shots")]
        public AudioSource oneShots;
        public AudioClip gearClip;
        public AudioClip touchdownClip;

        [Header("Mixing")]
        [Tooltip("Speed, in metres per second, at which the wind is at full volume.")]
        public float windFullSpeed = 220f;
        [Tooltip("How loud everything is overall.")]
        [Range(0f, 1f)] public float masterVolume = 0.85f;

        Aircraft plane;
        bool lastGearDown = true;
        bool lastOnGround = true;

        /// <summary>Set by the landing sequence while the engines are in reverse.</summary>
        public bool reverseThrust;

        void Start()
        {
            plane = Aircraft.Instance;

            if (plane == null)
            {
                Debug.LogWarning("[AUDIO] AircraftAudio found no aeroplane, so it will stay silent");
                enabled = false;
                return;
            }

            lastGearDown = plane.GearDown;
            lastOnGround = plane.OnGround;

            PlayIfReady(idle);
            PlayIfReady(power);
            PlayIfReady(wind);
            PlayIfReady(tyres);
            PlayIfReady(reverse);

            Debug.Log("[AUDIO] Engine, wind and tyre loops started");
        }

        static void PlayIfReady(AudioSource source)
        {
            if (source != null && source.clip != null && !source.isPlaying) source.Play();
        }

        void Update()
        {
            if (plane == null) return;

            float speedFraction = Mathf.Clamp01(plane.speed / Mathf.Max(1f, windFullSpeed));
            float thrust = Mathf.Clamp01(plane.throttle);

            // Engines: the two loops always add up to roughly one engine's worth of sound.
            Set(idle, (1f - thrust) * 0.55f + 0.2f, 1f);
            Set(power, thrust * 0.8f, 0.85f + thrust * 0.4f);

            // Wind: quiet until you are actually moving, then it takes over.
            Set(wind, speedFraction * speedFraction * 0.8f, 0.7f + speedFraction * 0.7f);

            // Tyres: rolling contact only.
            bool rolling = plane.OnGround && plane.GearDown && plane.speed > 1f;
            Set(tyres, rolling ? Mathf.Clamp01(plane.speed / 60f) * 0.7f : 0f, 0.8f + speedFraction * 0.5f);

            Set(reverse, reverseThrust ? 0.9f : 0f, 1f);

            WatchForEvents();
        }

        /// <summary>
        /// Fades a source towards a volume rather than snapping to it. A sudden jump in volume is
        /// heard as a click, which is the same problem the generated loops have to avoid.
        /// </summary>
        void Set(AudioSource source, float volume, float pitch)
        {
            if (source == null) return;

            float wanted = Mathf.Clamp01(volume) * masterVolume;
            source.volume = Mathf.MoveTowards(source.volume, wanted, 2.5f * Time.deltaTime);
            source.pitch = Mathf.MoveTowards(source.pitch, pitch, 1.5f * Time.deltaTime);
        }

        /// <summary>Fires the one-shots, by spotting the frame something changed.</summary>
        void WatchForEvents()
        {
            if (plane.GearDown != lastGearDown)
            {
                lastGearDown = plane.GearDown;
                OneShot(gearClip, 0.7f);
            }

            if (plane.OnGround && !lastOnGround)
            {
                OneShot(touchdownClip, 1f);
            }

            lastOnGround = plane.OnGround;
        }

        /// <summary>Plays a sound once. Safe to call when the clip was never generated.</summary>
        public void OneShot(AudioClip clip, float volume)
        {
            if (oneShots == null || clip == null) return;

            oneShots.PlayOneShot(clip, Mathf.Clamp01(volume) * masterVolume);
            Debug.Log("[AUDIO] " + clip.name);
        }
    }
}
