using UnityEngine;
using F = FlightSim.FlightLayout.Flight;

namespace FlightSim.Build
{
    /// <summary>
    /// Builds scene 3, the take-off and the flight (Assets/Scenes/03_Takeoff.unity).
    ///
    /// You start lined up on the runway with the engines idling. Push the throttle up, roll until
    /// the plane is fast enough, pull back, and fly. Press V at any point to watch from outside.
    /// Once the wheels are up and you are high enough, L begins the landing.
    ///
    /// The aeroplane is SharedParts.Airliner - the same one parked outside the window in scene 1 -
    /// with the cockpit from scene 2 fitted inside it, so the windscreen you look through in the
    /// air is the one you walked up to on the ground. The world around it is WorldParts, which
    /// scene 4 also uses, so you land back at the airport you left.
    ///
    /// Every number comes from FlightLayout.Flight, FlightLayout.Plane and FlightLayout.World.
    /// </summary>
    public static class FlightBuilder
    {
        public static void Build()
        {
            var scene = SceneKit.NewScene();

            WorldParts.Sky();
            WorldParts.Build(new GameObject("World").transform);

            Transform plane = Aeroplane();

            SceneKit.FlyingCamera(plane);
            GameSystems();

            SceneKit.Save(scene, FlightLayout.TakeoffScene);
        }

        /// <summary>
        /// The aeroplane, and everything bolted to it.
        ///
        /// The Aircraft component goes on an empty parent rather than on the model itself. That
        /// way the flight model only ever moves one object, and the shell, the cockpit and the
        /// sound all come along as children without knowing anything about flying.
        /// </summary>
        static Transform Aeroplane()
        {
            var root = new GameObject("Aeroplane");
            root.transform.position = F.PlaneStart;

            // Heading 90 degrees points the nose along +X, which is the way the runway runs.
            // Aircraft reads this rotation when it starts, so the scene file and the flight model
            // can never disagree about which way round the plane is.
            root.transform.rotation = Quaternion.Euler(0f, 90f, 0f);

            Transform model = Model(root.transform);
            Transform body = SharedParts.Airliner(model, Vector3.zero);
            FitCockpit(body);

            var aircraft = root.AddComponent<Aircraft>();
            aircraft.landingGear = body.Find("Landing Gear");
            aircraft.throttle = 0.05f;      // engines idling, brakes on

            if (aircraft.landingGear == null)
                Debug.LogWarning("[Flight Sim] The aeroplane has no 'Landing Gear' child, so the wheels will not retract");

            Sound(root.transform);
            SceneKit.PilotEye(root.transform);
            return root.transform;
        }

        /// <summary>
        /// The quarter turn that points the model where the aeroplane is going. See
        /// FlightLayout.Plane.ModelYaw - without it the plane flies sideways.
        /// </summary>
        static Transform Model(Transform root)
        {
            var model = Prim.Empty(root, "Model", Vector3.zero).transform;
            model.localRotation = Quaternion.Euler(0f, FlightLayout.Plane.ModelYaw, 0f);
            return model;
        }

        /// <summary>
        /// Drops the cockpit interior into the nose of the shell.
        ///
        /// The cockpit is built in the cabin's own coordinates, where the nose is at x = 10.4 and
        /// the floor is at y = 0. The shell has its nose at x = 18 and is centred on the middle of
        /// the fuselage. FlightLayout.Plane.CockpitOffset is the shift that lines the two up.
        /// </summary>
        static void FitCockpit(Transform body)
        {
            var mount = Prim.Empty(body, "Cockpit", FlightLayout.Plane.CockpitOffset).transform;
            CockpitParts.Cockpit(mount);
        }

        /// <summary>
        /// The engine, wind and tyre loops, plus the one-shots. Every clip is generated by
        /// AudioBank, so if Generate Audio has never been run they come back null and the game
        /// simply plays silently rather than failing to build.
        /// </summary>
        static void Sound(Transform plane)
        {
            var holder = Prim.Empty(plane, "Sound", Vector3.zero).transform;

            var audio = plane.gameObject.AddComponent<AircraftAudio>();
            audio.idle = SceneKit.Loop(holder, "Engine Idle", AudioBank.JetIdle);
            audio.power = SceneKit.Loop(holder, "Engine Power", AudioBank.JetPower);
            audio.wind = SceneKit.Loop(holder, "Wind", AudioBank.Wind);
            audio.tyres = SceneKit.Loop(holder, "Tyres", AudioBank.TyreRoll);
            audio.reverse = SceneKit.Loop(holder, "Reverse Thrust", AudioBank.Reverse);
            audio.oneShots = SceneKit.OneShotSource(holder, "One Shots");
            audio.gearClip = AudioBank.Load(AudioBank.Gear);
            audio.touchdownClip = AudioBank.Load(AudioBank.Touchdown);
        }

        /// <summary>The HUD, the fader and the flight readouts.</summary>
        static void GameSystems()
        {
            var hud = SceneKit.GameSystems(
                "Take-off - Runway 09",
                "Open the throttle with E, and pull back once you are fast enough",
                "W/S pitch    A/D roll    Q/E throttle    Space gear    V view    L land    Esc cursor");

            var flight = hud.gameObject.AddComponent<FlightHUD>();
            flight.offerLanding = true;
            flight.flightName = "FS 204";
        }
    }
}
